### PR TITLE
#2802845 Move template files from thunder_article to appropriate modules

### PR DESCRIPTION
**Pull request by steffenr**
* https://www.drupal.org/node/2802845

### CODE REVIEW

**Comment by goldquest** [comment]
This won't work, since we had to add the templates directory in the thunder_article manually to the theme engine. The problem was, that templates in modules won't override other templates. Only themes do that. 
See: https://github.com/BurdaMagazinOrg/thunder-distribution/blob/8.x-1.x/modules/thunder_article/thunder_article.module#L45

**Comment by goldquest** [comment]
I don't even know, if we should move these to the corresponding modules, since we will have modules, we don't have access to.
I would agree on a thunder_fia module, which handles all the fia stuff for thunder.

**Comment by steffenr** [comment]
Ah - ok - i was looking through my "themer" glasses ;) - sorry. 
As you suggested we should move these files to a more specific module, handling all the fbia stuff. In this case we could seperate things in a clearer way.

**Comment by steffenr** [comment]
@goldquest I'll close the PR and will add your comments to the d.o. issue. Would be great to split up the non-directly related templates / functionality into a separate module.

**Comment by chrfritsch** [comment]
Here is a PR for a thunder_fia module https://github.com/BurdaMagazinOrg/thunder-distribution/pull/111

**Pull request closed without merging**
