### PR TITLE
Issue #2969459 by chr.fritsch: Remove custom code for redirect after installation

### PR DESCRIPTION
**Pull request by chrfritsch**
Make sure these boxes are checked before submitting your pull request - thank you!

- [x] All coding styles are fulfilled. ([How to check for cs issues?](https://github.com/BurdaMagazinOrg/thunder-dev-tools/blob/master/README.md#code-style-guidelines))
- [x] All tests are running locally. ([How to run the test?](https://github.com/BurdaMagazinOrg/thunder-distribution/blob/develop/docs/development.md#how-to-run-the-tests))
- [x] Necessary update hooks are provided.
- [x] User roles have correct access for new introduced permission.
- [x] Every thunder module has a README.md in its root. Follow [this guidelines](https://www.drupal.org/node/2181737), but we don't need every topic.
- [x] Code is covered with well-balanced amount of inline comments.

If you are really awesome, then your feature is covered by additional tests. Well done!

### CODE REVIEW

**Comment by alexpott** [comment]
We need 8.6.x right? So this has to wait.

**Comment by chrfritsch** [comment]
This is the Thunder 3.x branch. We are using 8.6.x branch here because it will not be finished before that is released ;)

**Comment by dbosen** [comment]
But then we should depend on 8.6.x in the info.yml (is that possible?)

**Comment by chrfritsch** [comment]
Looks like drupal_verify_profile() is not able to handle something like   
`- system (>=8.6.0-dev)`
in the profile.info.yml

**Comment by chrfritsch** [comment]
We have the 8.6.x dependency in composer.json and in drupal-org-core.make. So I think we are fine.

**Review by mtodor — APPROVED** [review]

**Pull request merged**
