### PR TITLE
Integrate social buttons

### PR DESCRIPTION
**Pull request by chrfritsch**
Make sure these boxes are checked before submitting your pull request - thank you!

- [x] All coding styles are fulfilled. ([How to check for cs issues?](https://github.com/BurdaMagazinOrg/thunder-dev-tools/blob/master/README.md#code-style-guidelines))
- [x] All tests are running locally. ([How to run the test?](https://github.com/BurdaMagazinOrg/thunder-distribution/blob/8.x-1.x/docs/development.md#how-to-run-the-tests))
- [x] Necessary update hooks are provided.
- [x] User roles have correct access for new introduced permission.
- [x] Every thunder module has a README.md in its root. Follow [this guidelines](https://www.drupal.org/node/2181737), but we don't need every topic.
- [x] Code is covered with well-balanced amount of inline comments.

If you are really awesome, then your feature is covered by additional tests. Well done!

### CODE REVIEW

**Comment by dbosen** [comment]
The twitter link opens two popups on firefox, this has to be investigated before merging this.

**Comment by chrfritsch** [comment]
This happens in firefox for articles which have a twitter widget in their content

**Comment by chrfritsch** [comment]
I think this is an JS issue

**Comment by goldquest** [comment]
The problem is, that the twitter widget library still gets loaded. It reacts on clicks on links, which have an intent URL. See example here: http://jsbin.com/yaniguriri/1/edit?html,output
We have to remove the twitter library (which is actually, why shariff exists), or find a way to disable the twitter library for these links.

**Comment by goldquest** [comment]
AFAICS there is no possibility to have some attribute in the link, to disable it.

**Comment by goldquest** [comment]
Ok, I think the best solution is to stop the event bubbling on shariff links

**Comment by goldquest** [comment]
The code would look something like this:
```
jQuery('.shariff').click(function(e) {
  e.stopPropagation()
})
```

**Comment by chrfritsch** [comment]
If this fixes our problem, i am fine with that

**Comment by chrfritsch** [comment]
This also needs a checkbox in thunder updater

**Pull request merged**
